name: PlatformIO CI

on: [push, pull_request]

jobs:
  build_project:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio
          pip install wheel

      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio

      - name: Build Project
        run: pio run

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: .pio/build/**/firmware.bin

  run_unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build_project

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio
          pip install wheel

      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio

      - name: Run Unit Tests
        run: pio test -e native
